on:
  push:
    branches:
      - 'feature/*'
jobs:
  deploy:
    name: build
    runs-on: ubuntu-22.04
    environment: docker hub
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: build docker
      run: | 
        docker build --platform=linux/amd64 .



