on: push

jobs:
  deploy:
    name: build
    runs-on: ubuntu-22.04
    environment: docker hub
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{major}}.{{minor}}
    - name: calculate tags
      id: calculate_meta
      run: |
        tags=${{ steps.meta.outputs.tags }}
        tag=${tags[${#tags[@]} - 1]}
        echo "${tag%.*}.$((${tag##*.}+1))\n" >> $GITHUB_OUTPUT
    - name: build docker
      run: | 
        docker build -t ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ steps.calculate_meta.outputs.stdout }} .
    - name: push to docker hub
      run: |
        docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ steps.calculate_meta.outputs.stdout }} .



