on:
  push:
    branches:
      - 'release/v*.*.*'
jobs:
  build:
      runs-on: ubuntu-22.04
      environment: docker hub
      steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: calculate tags
        id: calculate_meta
        run: |
          REGISTRY=realmaxwebapp1
          REPOSITORY=my_backend

          next_page="https://registry.hub.docker.com/v2/namespaces/$REGISTRY/repositories/$REPOSITORY/tags?page=1&page_size=1000"
          tags=()
          result=$(curl -s "$next_page")
          tags=()

          if [ "$result" != "null" ]; then
            tag=`echo $result | jq -r '.results[].name' | grep -E '^1.*0'`
            tags=("${tags[@]}" $tag)
            while [ "$next_page" != "null" ];
            do
              result=$(curl -s "$next_page")
              tag=`echo $result | jq -r '.results[].name' | grep -E '^1.*0'`
              tags=("${tags[@]}" $tag)
              next_page=$(echo $result | jq -r '.next')
            done
          fi
          tag=${tags[0]}
          echo "Tag: $tag"
          if expr "$tag" : '^[0-9]\.' >/dev/null; then
            new_tag=`echo ${tag%.*}.$((${tag##*.}+1))`
          else
            new_tag=`echo 1.0.0`
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
      - name: build and push docker
        run: | 
          docker build --platform=linux/amd64 -t ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ steps.calculate_meta.outputs.new_tag }} --push .