on:
  push:
    branches:
      - master
jobs:
  build:
      runs-on: ubuntu-22.04
      environment: docker hub
      steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Go build
        run: |
          go build main.go
  docker-build-push:
      needs: build
      runs-on: ubuntu-22.04
      environment: docker hub
      steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: calculate tags
        id: calculate_meta
        run: |
          REGISTRY=realmaxwebapp
          REPOSITORY=my_backend
          next_page="https://registry.hub.docker.com/v2/namespaces/$REGISTRY/repositories/$REPOSITORY/tags?page=1&page_size=1000"

          TOKEN=$(curl -s -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\": \"${{ vars.DOCKER_USER_STG }}\", \"password\": \"${{ secrets.DOCKER_PASSWORD }}\"}" \
            https://hub.docker.com/v2/users/login/ | jq -r .token)


          result=$(curl -s -H "Authorization: JWT $TOKEN" \
            "$next_page" \
            | jq '.results[].name'| tr '\n' ' ')
          tags=()

          if [[ "${result[*]}" != *"not found"* ]]; then
            read -r -a result_array <<< $(echo $result)
            if [ "${#result_array[@]}" -gt 1 ]; then
              tag=${result_array[0]}
            else
              tag=$result
            fi
          fi
          echo "Tag: $tag"
          tagged=${tag//\"/}
          if expr "$tagged" : '^[0-9]\.' >/dev/null; then
            new_tag=`echo ${tagged%.*}.$((${tagged##*.}+1))`
          else
            new_tag=`echo 1.0.0`
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
      - name: build and push docker
        run: | 
          docker build --platform=linux/amd64 -t ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ steps.calculate_meta.outputs.new_tag }} --push .
      - name: Auto tag merge commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.calculate_meta.outputs.new_tag }}
          git push origin ${{ steps.calculate_meta.outputs.new_tag }}