on: push

jobs:
  deploy:
    name: build
    runs-on: ubuntu-22.04
    environment: docker hub
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: calculate tags
      id: calculate_meta
      run: |
        REGISTRY=realmaxwebapp
        REPOSITORY=my_backend

        next_page="https://registry.hub.docker.com/v2/namespaces/$REGISTRY/repositories/$REPOSITORY/tags?page=1&page_size=1000"
        tags=()
        while [ "$next_page" != "null" ]
        do
            result=$(curl -s "$next_page")
            tag=`echo $result | jq -r '.results[].name' | grep -E '^1.*0'`
            tags=("${tags[@]}" $tag)
            next_page=$(echo $result | jq -r '.next')
        done

        tag=${tags[0]}
        echo $tag
        new_tag=`echo ${tag%.*}.$((${tag##*.}+1))`
        echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
    - name: build and push docker
      run: | 
        docker build --platform=linux/arm64 -t ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ steps.calculate_meta.outputs.new_tag }} --push .



